language: node_js
node_js:
  - 10.15.3

services:
  - docker

branches:
  only:
    - development
    - qa
    - production
env:
  global:
    - REMOTE_IMAGE_URL_NYPLHEADER_DEV=491147561046.dkr.ecr.us-east-1.amazonaws.com/nyplheader
    - REMOTE_IMAGE_URL_NYPLHEADER_PRODUCTION=463786892988.dkr.ecr.us-east-1.amazonaws.com/nyplheader
    # AWS dev
    - secure: OhqeYc2DwKTLG4ywviFdiZextb+8Mae+XuIXYKX1lfeFIiQC9tflAmCz5y/TzKp+Mz9BfZwo7uZeW0XmMlVIKAhqjIShC4gM7cqX9p1xEkWUj6OwRtC0yT2rlv210NT/tsPDnTZo3KdD/+dBeNlknOax5H0/EqMqhw5pKJuLj6fLn3Tjgrgj4OFQR/JhFCbrCzpbAzJmlwGqP3QOlX181dbmPkUgQEuS2R05qujCwsWrzk0X9Kcm7BYCoxI1PfymDV4ZY0sR9TZGSqziRQsAIyMgm1yIY3o9sffar7oooxBqySU2Del/CoKFr1xfecdDL5xd5PbqpHFsUh3swZu2Qny5Ef4XYq6y0YOdQ8xC7bYUJEgvRv6EZxo7ZsS+eqCx3HIWtQyKXrT7qU8ChJtcCDj8jRZKrKtmR6xV3orlZCIzj4WVBj8L6IAd5ypUCkk+RrdhHFN69o19dR77ZIQ4dsX4cqQfwO+LnQtefHpF5kLS6vYJqd5WifAl6UA+84KfDspz32cIEXuuUqJqNGcG/0Ef1OTif7beENxkGsYOh1ujxG/tyW44ZeYW8Ep5jOEHa8iUCH5m3pvmnQBsgFvAxe1+lDnA1+pqIJus3gYKeByBEZoo06haOynsDBY4xNQZxtiC2V6uKzgUgKkrQf2iaitvqH9NMMzKZuGcBvwA648=
    # AWS prod
    - secure: cubP7e/Qs/LH31WGQTt3QSYgsBECmaZH4JOUSYVAOD8Axk0YTpCFVBbIzXd7XAfkEu7JMlDD2pvoc0WaIUAwDjh4wQ6Wx0wMpXfsREurdtEqkXyzdy8ECLSDix1rCFirlaEgDL0Auvp9my3hNpq16+NBP+08RizfRVzcKyaovw6e+VP6bKkZOk3m6dkTwH/u5iLR99oi+Q9s/KLHZmPMN8/R9p2OeXyWpR02IVOwkyywv/7A4D+5vd//+B7L1sn/+BcKVQvxDUaUiZdSXszd5HdwTv/zIozWn9rlontx92XQs7Cn6aMUPVxY0zH/4bA8kC54UrBxYN3eLyEWdH4DSz7FjVtO7v3Gh71659+kUjur0piFvYYDHIxWjRMue8vuo7Dd7jMdDimVBmBpfk2Cs6gp538RDC7FYE9cNpvE1m9bL8GcVzhp7iaGnFhqKl/zwx4V8zwb6UIbw10AkhowU/fxBtm9Y5jA9owgOGKXDrTSaOo83LK2uM37aOgdzxozKT1/e9rmBH+ZSvfGKo4G/sG2aOyhjRgQtB2dBaRJxySW6VJi6hldBd/idfkIw7oTE7oZFjBoRXZHrVgqr+qt/bmNk+eq2yZYgmm0c5lXjowsaGtL+qFcUSsU7mg1NVEQReYOt/xJa4tb7kcp7DOTfTqky1wl5HgD98ds1epkSao=

install: npm install

after_success:
  - cd $TRAVIS_BUILD_DIR
  - provisioning/deploy

script: echo "npm test temporarily disabled"

after_failure:
  - if [ -f $HOME/server.log ] ; then echo "Server log:" && cat $HOME/server.log ; fi

after_script:
  - rm -f $HOME/server.log

notifications:
  email:
    recipients: sysadmin@nypl.org
    on_success: always
    on_failure: always
