language: node_js
node_js:
  - 10.15.3

services:
  - docker

branches:
  only:
    - development
    - qa
    - production
env:
  global:
    - REMOTE_IMAGE_URL_NYPLHEADER_DEV=491147561046.dkr.ecr.us-east-1.amazonaws.com/nyplheader
    - REMOTE_IMAGE_URL_NYPLHEADER_PRODUCTION=463786892988.dkr.ecr.us-east-1.amazonaws.com/nyplheader
    # AWS dev
    - secure: G+V56oyMAzIhns1kg/M4vgmapgw9WMTrKJDceT+f05Dxdp3dApevBqlvmwS34xtDZPblI8UcCGEGuFjzqQ0EVrPe1lmrghdN9nA2pkpzfyAFRTVAQigFWmIR7kWCo/gJQHKHrKKnp7Up1Lpf6spz6rkzK1eExrs9UzlvCaNNbREi4WIGaE2KJXuTNgngHzvgBvalEHl0ttbww/yrkl47T+SR4sQT4A2PSP/LzZcPSfk3GhZ9QvvYdTc+PFevr0k7pghZbWOPUAuSfg6Dqn4SiFhBNrDl5GoxymdLyoERcdo7MZD5d3zVHY+MpYjUDNGP30ZDH15L9qPf/AZ13YvpH2Yd0gqFIrJEitNWT+zJj2+UW5hBvwEY8xNjsAFygYb4TYLHqjb4LXPAaDC/1q6h27D+rrRo0pcfty2VrJOIQ/qUdZvFv3gVjD8o9K7E+AclYdGybpbu7bBozBHK8B8wf0OWEEE8L3X9MKDFYuabXwlCtR9LB6iVJ9QgrVdz4cCX4EgwEZkOmFaJM4+xL2rOHToaP87N941F0wrsNzWu82USKsy94hI521+wPcQ3BAMaScE4o0KUTMHnjG2Um/Cz6jbKjl1zN6xakaRwNbN66zLNVOZ7UDeSF5/Sl8QjBKb334fSZFdUejI917i9SddQnJcjYVIbt3OI7+T0mZ5v/kY=
    # AWS prod
    - secure: BnY/lORFjLHRgKo/Amb40tFcVJH69GkZ1hwJ1XYShnE2z3y538Np3j4p6Mj2xkGF7Bmg65yjrxK8nQ2AvSItDrxE3K7vt0wcCYT/AevVZ73xd4iAjFjfLfldVpBEgeKb2hGJVcAcAv6wFsYpTJAhcIADmjTNpq7uOvOQYOlGwgaIlUBV5OBk0yD3cFOtWCzGulLKlFEjYqV7E4AIsXs9/mOEmdtz/dSEgpuxr5hh/py93/fljZCJvzQXoug+JKMXSY5s+ECR3h/Qj1WIU0/O9YEI+p9Y3D9JnRVilUwF93hFQ4kPJ3TsXBdFW0Ltoz43Jhc0grIrTh97ctUZhyNIcTD+bBvpg1smeUySH4r8pbR154hCe0VTXjDxYcLsuOrKZcLXKvxJBUOpNVxsNp4VahSsWdfRU1WlPEsAi+LevZwtG+KE9ifNj7uJPrbomRSi6p8e5WuSGV+73Sn9SNUlydBIj8iY0KF+ULhXJmQdE/3p88ed2RJDCgqSefc6K9Xcf2h0hJFnH3mP1unfrZ7/eWzy8/li+dAjHWD/DxgalSfyi+x1meRWpLqsJrDGKa7tofucGsbWPFPdhTJ7eIvCeAdOTLfb6GfEs+hqVLJxvZfiXM5rCzyzf3sWckqUA7+ZbU0sYLbzUNxiko9TpuryQDvj+i20aO3IbAh3EosiuI4=

install: npm install

after_success:
  - cd $TRAVIS_BUILD_DIR
  - provisioning/deploy

script: echo "npm test temporarily disabled"

after_failure:
  - if [ -f $HOME/server.log ] ; then echo "Server log:" && cat $HOME/server.log ; fi

after_script:
  - rm -f $HOME/server.log

notifications:
  email:
    recipients: sysadmin@nypl.org
    on_success: always
    on_failure: always
