language: node_js
node_js:
  - "10.15.3"
cache:
  directories:
  - node_modules
install: npm install
before_script: "echo 'No unit test coverage for Header App; Will attempt to build distribution assets as a safety'"
script: npm run dist
before_deploy: "echo 'Successfully built distribution assets; Preparing to deploy Header
  App to AWS'"
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: nypl-header-app
  env: nypl-header-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: nypl-header-production
  on:
    repo: NYPL/nypl-dgx-react-header
    branch: master
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: nypl-header-app
  env: nypl-header-qa-1
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: nypl-header-qa
  on:
    repo: NYPL/nypl-dgx-react-header
    branch: qa
# - provider: elasticbeanstalk
#   skip_cleanup: true
#   access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
#   secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
#   region: us-east-1
#   app: nypl-header-app
#   env: nypl-header-development
#   bucket_name: elasticbeanstalk-us-east-1-224280085904
#   bucket_path: nypl-header-development
#   on:
#     repo: NYPL/nypl-dgx-react-header
#     branch: development
after_deploy: echo 'Successfully executed deploy trigger for Header App on AWS'
env:
  global:
    secure: TpnWUemRm5VO+fuUvpsOivelxwPzWiB6PsNo1jSgERZOnMBkA+K7UqsWqeLP9uzNcsaY1FP1oduLkB/bFYZksRB3sCefskXAEUk356kQLUhkn36beT0rAhPWM1yUMurLPRpTTX+bH05KC6H3KSDCfiusuaeBc1My5DakSGwQNlrscf9LViam+TO3nr/I6RrXPd1ncIVENSo10NyLZGIv1X8zHeU4gLoX6HBrofmZPJWC2wZNZ37tI7QXQn9CmzESWpZEL7Rfx8ThUEeFvxVNxPldYOQY3GWCzaxf2AK2seT7PmxkRsEP2qvwLR1phKHIOLBOClBoVjpZiaP/9yJqBxiKDxk5elarY8TLUpn7jN0xFGByOfi1rTfbdoV+6tMaooVYR9vdeLlzE2jOGikO2WMKVomFTFCLUoVN4OLzNmUbFSRqtQLPlZ1x5eGd3+JyTsAAZZjf/C7wKZs/H92GPLXAo3dJKTACl71FlC2Xk5KPFq0HXRK+vdvTWDSXSCJ47Xns6vFZeDrKoG6GfO0/U4h8qYJbW70DRfksxDXrZf75TwxclbRyZzyUV6ZT2sr+LvS5I0kzQrTbjPs/2lxsNSr13trVU5fico40t4sc+QCK1faB6b1tvOaCCFa2fUJrYxhZTez01IyBEiEKj6ZgVOz88VXNIEvfP1XCZujgYpk=
