language: node_js
node_js:
  - 6.11.5

services:
  - docker

branches:
  only:
    - development
    - qa
    - production
env:
  global:
    secure: TpnWUemRm5VO+fuUvpsOivelxwPzWiB6PsNo1jSgERZOnMBkA+K7UqsWqeLP9uzNcsaY1FP1oduLkB/bFYZksRB3sCefskXAEUk356kQLUhkn36beT0rAhPWM1yUMurLPRpTTX+bH05KC6H3KSDCfiusuaeBc1My5DakSGwQNlrscf9LViam+TO3nr/I6RrXPd1ncIVENSo10NyLZGIv1X8zHeU4gLoX6HBrofmZPJWC2wZNZ37tI7QXQn9CmzESWpZEL7Rfx8ThUEeFvxVNxPldYOQY3GWCzaxf2AK2seT7PmxkRsEP2qvwLR1phKHIOLBOClBoVjpZiaP/9yJqBxiKDxk5elarY8TLUpn7jN0xFGByOfi1rTfbdoV+6tMaooVYR9vdeLlzE2jOGikO2WMKVomFTFCLUoVN4OLzNmUbFSRqtQLPlZ1x5eGd3+JyTsAAZZjf/C7wKZs/H92GPLXAo3dJKTACl71FlC2Xk5KPFq0HXRK+vdvTWDSXSCJ47Xns6vFZeDrKoG6GfO0/U4h8qYJbW70DRfksxDXrZf75TwxclbRyZzyUV6ZT2sr+LvS5I0kzQrTbjPs/2lxsNSr13trVU5fico40t4sc+QCK1faB6b1tvOaCCFa2fUJrYxhZTez01IyBEiEKj6ZgVOz88VXNIEvfP1XCZujgYpk=

install: npm install

after_success:
  - cd $TRAVIS_BUILD_DIR
  - provisioning/deploy

script: echo "npm test temporarily disabled"

after_failure:
  - if [ -f $HOME/server.log ] ; then echo "Server log:" && cat $HOME/server.log ; fi

after_script:
  - rm -f $HOME/server.log

notifications:
  email:
    recipients: sysadmin@nypl.org
    on_success: always
    on_failure: always
